export { createPluginConfig } from './factory';
export type {
  PluginOptions,
  FormOutletConfig,
  CollectionOutletConfig,
  PageConfig,
  MainNavigationTabConfig,
  SidebarPanelConfig,
  SidebarConfig,
  FieldExtensionConfig,
  FieldExtensionOverrideConfig,
  ModalConfig,
  ConfigScreenConfig,
  DropdownActionConfig,
  DropdownActionType,
  OnBootHandler,
  OnBeforeItemUpsertHandler,
  OnBeforeItemsDestroyHandler,
  OnBeforeItemsPublishHandler,
  OnBeforeItemsUnpublishHandler,
} from './types';
